### PR TITLE
Use 2.11 api

### PR DESCRIPTION
**Pull request by dpursehouse**

### CODE REVIEW

**Comment by dpursehouse** [comment]
Note that the 2.11-SNAPSHOT version of the plugin API is not published; it needs to be built locally.

**Comment by rinrinne** [comment]
Why doesn't Gerrit keep secure regarding BC? I have to manage more than 2 branches to support the past version...

**Comment by rinrinne** [comment]
Now changed settings in travis to prevent to build a branch without `.travis.yml`. So please rename `.travis.yml` to e.g. `dot.travis.yml`

**Comment by dpursehouse** [comment]
> Why doesn't Gerrit keep secure regarding BC?

Sorry, I don't understand this question.  Please rephrase it.

> I have to manage more than 2 branches to support the past version...

This is the case for all plugins.  Unfortunately, you have chosen not to contribute this one via gerrit-review like most of the others, so there is less support for creation of stable-2.x branches and keeping a working build across API versions.

I'm only contributing these fixes here out of necessity, since we want to use it with 2.11-rc0 Gerrit version internally at Sony Mobile.

All the other commonly used plugins hosted on gerrit-review have already been fixed to build with the latest API.

**Comment by rinrinne** [comment]
> Sorry, I don't understand this question. Please rephrase it.

Why does Gerrit stop providing `ChangeListener`? I think there is a way to leave it as the same name because it is interface class...

> All the other commonly used plugins hosted on gerrit-review have already been fixed to build with the latest API.

I think plugin repository on gerrit-review also has the same issue. As you mentioned, `master` branch might be able to follow the latest in core. But if a feature which is merged to `master` want to be introduced to the past API version, plugin developer have to checkout the proper tag to new branch then cherry-picked it.

**Comment by rinrinne** [comment]
I cannot merge this into `master`. Instead I will open new branch for 2.11 api.

**Comment by dpursehouse** [comment]
> I think plugin repository on gerrit-review also has the same issue. As you mentioned, master branch might be able to follow the latest in core. But if a feature which is merged to master want to be introduced to the past API version, plugin developer have to checkout the proper tag to new branch then cherry-picked it.

On gerrit-review we don't put new features on the stable branches, only bugfixes.  New development stays on master.  If anybody wants a new feature to work on an older version, they have to backport it themselves.

> Why does Gerrit stop providing ChangeListener? I think there is a way to leave it as the same name because it is interface class...

Feel free to submit a patch on stable-2.11 if you think it can be fixed.

**Comment by rinrinne** [comment]
This is a plugin to support all official releases as far as possible. Not including rc, beta, etc. So I cannot follow Gerrit development policy as you mentioned.

> Feel free to submit a patch on stable-2.11 if you think it can be fixed.

Unfortunately I don't have enough of ability for that. All I know is that Java has an ability to do that. 
So I would not do that.

**Comment by dpursehouse** [comment]
> Unfortunately I don't have enough of ability for that. All I know is that Java has an ability to do that. 
So I would not do that.

OK, then if you want it to be fixed please raise an issue on the Gerrit tracker.

http://code.google.com/p/gerrit/issues/list

**Comment by rinrinne** [comment]
Now open `api-2.11` branch. I will cherry-pick 18f2cb7. OK?

**Comment by dpursehouse** [comment]
Submitted PR #16 instead.

**Comment by rinrinne** [comment]
OK.

**Pull request closed without merging**
